### ISSUE TITLE
filterbank.py broken

### ISSUE THREAD

**Issue by griffinfoster** [UCBerkeleySETI/filterbank#6]
When running filterbank.py I get the following error, previous versions of the script run fine on the file.

Traceback (most recent call last):
  File "/home/obs/sw/filterbank/filterbank.py", line 893, in <module>
    fil.info()
  File "/home/obs/sw/filterbank/filterbank.py", line 634, in info
    for key, val in self.header.items():
AttributeError: 'Filterbank' object has no attribute 'header'

**Comment by telegraphic** [comment]
@griffinfoster can I get a little more info? What file did you use, and was this using `filterbank.py` on the command line or importing stuff?

**Comment by griffinfoster** [comment]
I am running the script, this occurs with any file I tried on blc00. Matt has an older version of the script which works fine with the same files. See ~mattl/filterbank.py on blc00

**Comment by telegraphic** [comment]
On blc00 at GBT? It seems to work for me:
```
dprice@blc00:~/filterbank$ ./filterbank.py /datax2/dibas.20160512/AGBT16A_999_186/GUPPI/A/blc00_guppi_57521_01003_HIP44064_0006.gpuspec.0000.fil

    telescope_id :                                6
     rawdatafile : guppi_57521_01003_HIP44064_0006.0000.raw
     source_name :                         HIP44064
          tstart :                    57521.0116088
       data_type :                                1
          nchans :                         66125824
           ibeam :                                1
           tsamp :                     17.986224128
            foff :               -2.83550341845e-06
         src_raj :                      8:58:27.024
         src_dej :                         35:48:09
          nbeams :                                1
        az_start :                              0.0
            fch1 :                    2251.46484233
        za_start :                              0.0
      machine_id :                               20
            nifs :                                1
           nbits :                               32

Num ints in file :                               16
      Data shape :                (16, 1, 66125824)
Start freq (MHz) :                    2063.96484517
 Stop freq (MHz) :                    2251.46484233

dprice@blc00:~/filterbank$ git log
commit 116fe4543a5c0c9852e5232bf57f9e678a7cdab2
Author: Danny Price <dan@thetelegraphic.com>
Date:   Fri Oct 14 14:50:51 2016 -0700

    Can now read and write filterbank files in HDF5
```

**Comment by siemion** [comment]
This is blc00 at UCB

**Comment by telegraphic** [comment]
Ok, the issue was that this node doesn't have HDF5, so code was entering the wrong if:else statement. Fixed and closing now.
